import { TrackableProcess } from "./Tracker";

const trackableProcesses: TrackableProcess[] = [
	{
		title: "New Product Launch",
		progress: 10,
		tags: ["product", "launch", "marketing"],
		createdBy: "John Doe",
		assignedTo: "Jane Smith",
	},
	{
		title: "Website Redesign",
		progress: 25,
		tags: ["website", "design", "UI/UX"],
		createdBy: "Alice Johnson",
		assignedTo: "Bob Brown",
	},
	{
		title: "Market Research",
		progress: 50,
		tags: ["research", "market", "analysis"],
		createdBy: "Chris Evans",
		assignedTo: "Diana Prince",
	},
	{
		title: "Mobile App Development",
		progress: 40,
		tags: ["mobile", "app", "development"],
		createdBy: "Eve Adams",
		assignedTo: "Frank White",
	},
	{
		title: "Database Migration",
		progress: 70,
		tags: ["database", "migration", "backend"],
		createdBy: "Grace Hopper",
		assignedTo: "Hank Green",
	},
	{
		title: "Sales Campaign",
		progress: 20,
		tags: ["sales", "campaign", "marketing"],
		createdBy: "Ivy Lane",
		assignedTo: "Jack Black",
	},
	{
		title: "Customer Feedback Analysis",
		progress: 60,
		tags: ["customer", "feedback", "analysis"],
		createdBy: "Ken Adams",
		assignedTo: "Laura Palmer",
	},
	{
		title: "Cloud Infrastructure Setup",
		progress: 30,
		tags: ["cloud", "infrastructure", "setup"],
		createdBy: "Michael Scott",
		assignedTo: "Pam Beesly",
	},
	{
		title: "SEO Optimization",
		progress: 45,
		tags: ["SEO", "optimization", "marketing"],
		createdBy: "Oscar Martinez",
		assignedTo: "Dwight Schrute",
	},
	{
		title: "Employee Training Program",
		progress: 80,
		tags: ["employee", "training", "HR"],
		createdBy: "Ryan Howard",
		assignedTo: "Angela Martin",
	},
	{
		title: "Quarterly Financial Report",
		progress: 90,
		tags: ["financial", "report", "quarterly"],
		createdBy: "Stanley Hudson",
		assignedTo: "Phyllis Vance",
	},
	{
		title: "Event Planning",
		progress: 35,
		tags: ["event", "planning", "logistics"],
		createdBy: "Jim Halpert",
		assignedTo: "Karen Filippelli",
	},
	{
		title: "Supplier Contract Negotiation",
		progress: 50,
		tags: ["supplier", "contract", "negotiation"],
		createdBy: "Andy Bernard",
		assignedTo: "Erin Hannon",
	},
	{
		title: "Social Media Campaign",
		progress: 65,
		tags: ["social media", "campaign", "marketing"],
		createdBy: "Darryl Philbin",
		assignedTo: "Kelly Kapoor",
	},
	{
		title: "Risk Assessment",
		progress: 40,
		tags: ["risk", "assessment", "compliance"],
		createdBy: "Toby Flenderson",
		assignedTo: "Holly Flax",
	},
	{
		title: "New Employee Onboarding",
		progress: 55,
		tags: ["employee", "onboarding", "HR"],
		createdBy: "Jan Levinson",
		assignedTo: "David Wallace",
	},
	{
		title: "Brand Strategy Development",
		progress: 20,
		tags: ["brand", "strategy", "marketing"],
		createdBy: "Roy Anderson",
		assignedTo: "Pam Beesly",
	},
	{
		title: "System Security Upgrade",
		progress: 75,
		tags: ["security", "system", "upgrade"],
		createdBy: "Robert California",
		assignedTo: "Clark Green",
	},
	{
		title: "Content Management System Implementation",
		progress: 45,
		tags: ["content", "management", "system"],
		createdBy: "Nellie Bertram",
		assignedTo: "Pete Miller",
	},
	{
		title: "Inventory Management",
		progress: 60,
		tags: ["inventory", "management", "logistics"],
		createdBy: "Gabe Lewis",
		assignedTo: "Dunder Mifflin Warehouse",
	},
	{
		title: "Email Marketing Campaign",
		progress: 30,
		tags: ["email", "marketing", "campaign"],
		createdBy: "Clark Green",
		assignedTo: "Erin Hannon",
	},
	{
		title: "Legal Compliance Audit",
		progress: 85,
		tags: ["legal", "compliance", "audit"],
		createdBy: "Josh Porter",
		assignedTo: "Charles Miner",
	},
	{
		title: "Quality Assurance Testing",
		progress: 50,
		tags: ["quality", "assurance", "testing"],
		createdBy: "Ryan Howard",
		assignedTo: "Kelly Kapoor",
	},
];

export default trackableProcesses;
